sudo: false
language: android
jdk: oraclejdk8
script: "./gradlew assembleDebug"
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
notifications:
  email: false
deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key:
    secure: # do command: `travis encrypt --add deploy.secret_access_key`to populate this field or generate the encrypted value
  bucket: "jisort"
  skip_cleanup: true
  local-dir: app/build/outputs/apk # will upload everything in this dir into the root of your s3 bucket
